In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [2]:
df = pd.read_csv('df_model_v6.csv')

In [3]:
def missing_values_table(df):
        # Total missing values
        mis_val = df.isnull().sum()
        
        # Percentage of missing values
        mis_val_percent = 100 * df.isnull().sum() / len(df)
        
        # Make a table with the results
        mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
        
        # Rename the columns
        mis_val_table_ren_columns = mis_val_table.rename(
        columns = {0 : 'Missing Values', 1 : '% of Total Values'})
        
        # Sort the table by percentage of missing descending
        mis_val_table_ren_columns = mis_val_table_ren_columns[
            mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
        '% of Total Values', ascending=False).round(1)
        
        # Print some summary information
        print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
            "There are " + str(mis_val_table_ren_columns.shape[0]) +
              " columns that have missing values.")
        
        # Return the dataframe with missing information
        return mis_val_table_ren_columns

In [4]:
missing_values = missing_values_table(df)
missing_values

Your selected dataframe has 55 columns.
There are 17 columns that have missing values.

                         Missing Values  % of Total Values
Frequnecy_comment_12M             39220               74.8
Total_nb_likes                    39220               74.8
Recency_comment                   39220               74.8
LastCommentDate                   39220               74.8
Avg_commision_y                   39220               74.8
NB_categories_commented           39220               74.8
NB_products_commented             39220               74.8
Total_nb_wish                     39220               74.8
Total_likes                       10889               20.8
Total_wishes                      10889               20.8
Recency_liked                     10889               20.8
LastLikeDate                      10889               20.8
Avg_commision_x                   10889               20.8
NB_categories_liked               10889               20.8
NB_products_liked                 10889               20.8
Total_MMAO_NB                     10889               20.8
Frequnecy_like_12M                10889               20.8

Plots: 

- Countplot for data 

- Heatmap missing data

- Heatmap correlation

- Boxplot for data with Repeater 

- Density plots

- Order value distribution & plots

In [6]:
# check if two dataframes are equal 

df1 = pd.read_csv('df_model_v6.csv')
df2 = pd.read_csv('old_dataframes\df_model_v5.csv')

df1.equals(df2)

False

In [10]:
df1.shape

(52434, 55)

In [9]:
df2.shape

(52434, 55)

In [7]:
df1.head()

,ID_BUYER,RANK_BUYER,RANK_WITHIN_SEGMENT,ID_SEGMENT,ORDER_VALUE_RANGE,DATE_NEW_BUYER,DATE_CREATION,DATE_LAST_LOGIN,INACTIVE,NB_SOLD,NB_PUBLISHED,NB_PURCHASED,NL_REACTIVITY_GROUP,ID_RFM_BUYER,RFM_BUYER,USER_SEGMENT,DATE_LAST_PURCHASE,DATE_FIRST_PURCHASE,BUYER_SEGMENT,REPEATER,CLTV,NB_OFFERS,AVG_OFFERS,NB_DAYS_ONLINE,ID_CATEGORY,ID_SUBCATEGORY,ID_BRAND,ID_PAYMENT_TYPE,ORDER_MARKETING_CHANNEL,DEPOSIT_PRICE,PRICE_SOLD_GMV,NB_ITEMS,DISCOUNT_AMOUNT_GMV,BUYER_FEE_GMV,MMAO_PRICE_DROP,VOUCHER_REVENUE,ID_CONDITION,ID_GENDER,Total_likes,Total_wishes,Total_MMAO_NB,NB_products_liked,NB_categories_liked,Avg_commision_x,LastLikeDate,Recency_liked,Frequnecy_like_12M,Total_nb_likes,Total_nb_wish,NB_products_commented,NB_categories_commented,Avg_commision_y,LastCommentDate,Recency_comment,Frequnecy_comment_12M
0,571,1.0,17,0,[500-1000[,2022-01-20,2009-10-21 13:09:01.000,2023-01-03 21:35:12.000,0,75,141,1,D,5.0,Need To Engage,Highly Engaged,2022-01-20 23:43:02.000,2022-01-20 23:43:02.000,High potential one timers,0.0,5850.719086,21.0,1.909091,51,13.0,511.0,50,56,affiliation,526.932084,540.216086,1.0,24.009604,18.007203,0.000000,24.009604,3.0,1.0,1193.0,103.0,270.0,26.0,3.0,149.331257,2022-12-27 23:15:30,16.0,26.0,0.0,1560.0,9.0,3.0,86.742352,2022-11-17 10:06:58,56.0,1383.0
1,6048,1.0,345,0,[1000-5000[,2022-12-07,2010-02-02 17:23:20.000,2023-01-10 01:49:43.000,0,0,0,1,D,3.0,Potential Loyal,Highly Engaged,2022-12-07 13:24:11.000,2022-12-07 13:24:11.000,High potential repeaters,1.0,2500.000000,4.0,1.000000,8,141.0,59.0,50,56,affiliation,0.000000,2016.101923,1.0,0.000000,15.000000,17.500228,0.000000,4.0,1.0,22463.0,2505.0,3977.0,267.0,5.0,264.692792,2023-01-10 02:01:13,3.0,142.0,0.0,5061.0,2.0,1.0,212.005318,2021-12-26 15:20:44,382.0,0.0
2,16737,1.0,14,0,[300-500[,2022-03-05,2010-08-12 12:41:33.000,2023-01-13 00:40:29.000,0,0,1,2,D,3.0,Potential Loyal,Highly Engaged,2022-11-18 10:34:19.000,2022-03-05 22:58:08.000,High potential repeaters,1.0,840.000000,15.0,1.153846,83,[ 14. 141.],[ 59. 609.],[ 14 471],[56 65],['crm' 'sem buyer'],799.268519,420.000000,1.0,0.000000,0.000000,110.697740,0.000000,9.0,1.0,2617.0,55.0,730.0,63.0,3.0,159.654061,2023-01-13 00:42:22,0.0,63.0,0.0,0.0,1.0,1.0,58.333333,2022-11-29 17:47:30,44.0,1.0
3,18735,1.0,4493,0,[150-300[,2022-04-29,2010-09-06 19:19:31.000,2022-12-12 15:04:09.000,0,0,0,2,B,5.0,Need To Engage,At High Risk,2022-04-29 15:36:07.000,2022-04-29 15:36:07.000,Low potential one timers,0.0,165.000000,130.0,1.710526,3,12.0,39.0,106,56,crm,100.000000,82.500000,2.0,0.000000,0.000000,0.000000,0.000000,4.0,2.0,3225.0,230.0,423.0,59.0,5.0,21.625193,2022-09-06 22:10:31,128.0,59.0,0.0,924.0,1.0,1.0,13.986014,2022-05-05 13:36:17,252.0,154.0
4,47068,1.0,6,0,[150-300[,2022-03-09,2011-01-25 14:20:00.000,2022-12-18 13:35:28.000,0,3,5,2,Active_Non_Targeted,3.0,Potential Loyal,Need Attention,2022-06-24 19:22:02.000,2022-03-09 09:09:05.000,Low quality repeaters,1.0,425.616576,4.0,1.333333,0,[ 12. 141.],[ 59. 137.],4783,56,['crm' 'sem buyer'],136.716329,134.628788,1.0,0.000000,0.000000,-4.233308,0.000000,9.5,1.0,152.0,6.0,25.0,4.0,2.0,17.095632,2022-09-30 19:39:00,104.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df2.head()

,ID_BUYER,RANK_BUYER,RANK_WITHIN_SEGMENT,ID_SEGMENT,ORDER_VALUE_RANGE,DATE_NEW_BUYER,DATE_CREATION,DATE_LAST_LOGIN,INACTIVE,NB_SOLD,NB_PUBLISHED,NB_PURCHASED,NL_REACTIVITY_GROUP,ID_RFM_BUYER,RFM_BUYER,USER_SEGMENT,DATE_LAST_PURCHASE,DATE_FIRST_PURCHASE,BUYER_SEGMENT,REPEATER,CLTV,NB_OFFERS,AVG_OFFERS,NB_DAYS_ONLINE,ID_CATEGORY,ID_SUBCATEGORY,ID_BRAND,ID_PAYMENT_TYPE,ORDER_MARKETING_CHANNEL,DEPOSIT_PRICE,PRICE_SOLD_GMV,NB_ITEMS,DISCOUNT_AMOUNT_GMV,BUYER_FEE_GMV,MMAO_PRICE_DROP,VOUCHER_REVENUE,ID_CONDITION,ID_GENDER,Total_likes,Total_wishes,Total_MMAO_NB,NB_products_liked,NB_categories_liked,Avg_commision_x,LastLikeDate,Recency_liked,Frequnecy_like_12M,Total_nb_likes,Total_nb_wish,NB_products_commented,NB_categories_commented,Avg_commision_y,LastCommentDate,Recency_comment,Frequnecy_comment_12M
0,571,1.0,17,0,[500-1000[,2022-01-20,2009-10-21 13:09:01.000,2023-01-03 21:35:12.000,0,75,141,1,D,5.0,Need To Engage,Highly Engaged,2022-01-20 23:43:02.000,2022-01-20 23:43:02.000,High potential one timers,0.0,5850.719086,21.0,1.909091,51,13.0,511.0,50,56,affiliation,526.932084,540.216086,1.0,24.009604,18.007203,0.000000,24.009604,3.0,1.0,1193.0,103.0,270.0,26.0,3.0,149.331257,2022-12-27 23:15:30,16.0,26.0,0.0,1560.0,9.0,3.0,86.742352,2022-11-17 10:06:58,56.0,1383.0
1,6048,1.0,345,0,[1000-5000[,2022-12-07,2010-02-02 17:23:20.000,2023-01-10 01:49:43.000,0,0,0,1,D,3.0,Potential Loyal,Highly Engaged,2022-12-07 13:24:11.000,2022-12-07 13:24:11.000,High potential repeaters,0.0,2500.000000,4.0,1.000000,8,141.0,59.0,50,56,affiliation,0.000000,2016.101923,1.0,0.000000,15.000000,17.500228,0.000000,4.0,1.0,22463.0,2505.0,3977.0,267.0,5.0,264.692792,2023-01-10 02:01:13,3.0,142.0,0.0,5061.0,2.0,1.0,212.005318,2021-12-26 15:20:44,382.0,0.0
2,16737,1.0,14,0,[300-500[,2022-03-05,2010-08-12 12:41:33.000,2023-01-13 00:40:29.000,0,0,1,2,D,3.0,Potential Loyal,Highly Engaged,2022-11-18 10:34:19.000,2022-03-05 22:58:08.000,High potential repeaters,0.0,840.000000,15.0,1.153846,83,[ 14. 141.],[ 59. 609.],[ 14 471],[56 65],['crm' 'sem buyer'],799.268519,420.000000,1.0,0.000000,0.000000,110.697740,0.000000,9.0,1.0,2617.0,55.0,730.0,63.0,3.0,159.654061,2023-01-13 00:42:22,0.0,63.0,0.0,0.0,1.0,1.0,58.333333,2022-11-29 17:47:30,44.0,1.0
3,18735,1.0,4493,0,[150-300[,2022-04-29,2010-09-06 19:19:31.000,2022-12-12 15:04:09.000,0,0,0,2,B,5.0,Need To Engage,At High Risk,2022-04-29 15:36:07.000,2022-04-29 15:36:07.000,Low potential one timers,0.0,165.000000,130.0,1.710526,3,12.0,39.0,106,56,crm,100.000000,82.500000,2.0,0.000000,0.000000,0.000000,0.000000,4.0,2.0,3225.0,230.0,423.0,59.0,5.0,21.625193,2022-09-06 22:10:31,128.0,59.0,0.0,924.0,1.0,1.0,13.986014,2022-05-05 13:36:17,252.0,154.0
4,47068,1.0,6,0,[150-300[,2022-03-09,2011-01-25 14:20:00.000,2022-12-18 13:35:28.000,0,3,5,2,Active_Non_Targeted,3.0,Potential Loyal,Need Attention,2022-06-24 19:22:02.000,2022-03-09 09:09:05.000,Low quality repeaters,0.0,425.616576,4.0,1.333333,0,[ 12. 141.],[ 59. 137.],4783,56,['crm' 'sem buyer'],136.716329,134.628788,1.0,0.000000,0.000000,-4.233308,0.000000,9.5,1.0,152.0,6.0,25.0,4.0,2.0,17.095632,2022-09-30 19:39:00,104.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df1.REPEATER.value_counts()

0.0    37176
1.0    15258
Name: REPEATER, dtype: int64

In [13]:
df2.REPEATER.value_counts()

0.0    42877
1.0     9557
Name: REPEATER, dtype: int64